### ISSUE TITLE
failure to compile SimpleClient example for ESP8266

### ISSUE THREAD

**Issue by 2114L3** [fredilarsen/ReconnectingMqttClient#4]
examples/ESP8266_32/SimpleClient/SimpleClient.ino has a dependency on ReconnectingMqttClient.h which includes PJONEthernetTCP.h

PJONEthernetTCP.h is documented to not support the ESP8266

can i get this example to compile on a ESP8266?

**Comment by 2114L3** [comment]
flow on impact to MQTTTranslate
https://github.com/gioblu/PJON/issues/420#issuecomment-1546906154

**Comment by fredilarsen** [comment]
@2114L3 I just tested building the ESP8266_32/SimpleClient example from the master branch for the ESP8266 board "LOLIN (WEMOS)  D1 R2 & mini", and it works without changes.

I did use Arduino IDE 1.8.13 which is rather old.
I also tested compiling with Arduino 2.1, and that works as well.

**Comment by 2114L3** [comment]
Thank you!  noting your board quote was slightly different to my selection - i was on ESP3266 community 2.4.1, updating this to 3.1.2 has resolved my issues.

Arduino IDE 1.8.19 , ReconnectingMqttClient 1.2.0, ESP8266 Community 3.1.2 compiles 
thank for the great project
